//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbTeknikServisEntities : DbContext
    {
        public DbTeknikServisEntities()
            : base("name=DbTeknikServisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TblAdmin> TblAdmin { get; set; }
        public virtual DbSet<TblAraclar> TblAraclar { get; set; }
        public virtual DbSet<TblArizaDetay> TblArizaDetay { get; set; }
        public virtual DbSet<TblCari> TblCari { get; set; }
        public virtual DbSet<TblDepartman> TblDepartman { get; set; }
        public virtual DbSet<TblFaturaBilgi> TblFaturaBilgi { get; set; }
        public virtual DbSet<TblFaturaDetay> TblFaturaDetay { get; set; }
        public virtual DbSet<TblGider> TblGider { get; set; }
        public virtual DbSet<TblHakkimizda> TblHakkimizda { get; set; }
        public virtual DbSet<TblIletisim> TblIletisim { get; set; }
        public virtual DbSet<TblKategori> TblKategori { get; set; }
        public virtual DbSet<TblNotlarım> TblNotlarım { get; set; }
        public virtual DbSet<TblPersonel> TblPersonel { get; set; }
        public virtual DbSet<TblUrunHareket> TblUrunHareket { get; set; }
        public virtual DbSet<TblUrunler> TblUrunler { get; set; }
        public virtual DbSet<TblUrunTakip> TblUrunTakip { get; set; }
        public virtual DbSet<TblUrunKabul> TblUrunKabul { get; set; }
    
        public virtual ObjectResult<UrunKategori_Result> UrunKategori()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UrunKategori_Result>("UrunKategori");
        }
    
        public virtual ObjectResult<string> maksimumkategoriurun()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("maksimumkategoriurun");
        }
    
        public virtual ObjectResult<string> maksimumurunmarka()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("maksimumurunmarka");
        }
    }
}
