//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPersonel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblPersonel()
        {
            this.TblFaturaBilgi = new HashSet<TblFaturaBilgi>();
            this.TblUrunHareket = new HashSet<TblUrunHareket>();
            this.TblUrunKabul = new HashSet<TblUrunKabul>();
        }
    
        public short ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<byte> Departman { get; set; }
        public string Fotograf { get; set; }
        public string Mail { get; set; }
        public string Telefon { get; set; }
        public string CepTelefonu { get; set; }
        public string Adres { get; set; }
    
        public virtual TblDepartman TblDepartman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFaturaBilgi> TblFaturaBilgi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUrunHareket> TblUrunHareket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUrunKabul> TblUrunKabul { get; set; }
    }
}
