//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUrunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblUrunler()
        {
            this.TblUrunHareket = new HashSet<TblUrunHareket>();
        }
    
        public int ID { get; set; }
        public string UrunAd { get; set; }
        public string Marka { get; set; }
        public Nullable<decimal> AlisFiyati { get; set; }
        public Nullable<decimal> SatisFiyati { get; set; }
        public Nullable<short> Stok { get; set; }
        public Nullable<byte> Kategori { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual TblKategori TblKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUrunHareket> TblUrunHareket { get; set; }
    }
}
