//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUrunKabul
    {
        public int ID { get; set; }
        public Nullable<int> Cari { get; set; }
        public Nullable<short> Personel { get; set; }
        public Nullable<System.DateTime> GelisTarihi { get; set; }
        public Nullable<System.DateTime> CikisTarihi { get; set; }
        public string UrunSeriNo { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string UrunDurumDetay { get; set; }
    
        public virtual TblCari TblCari { get; set; }
        public virtual TblPersonel TblPersonel { get; set; }
    }
}
